version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./vendor/bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  mysql_data:
