version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: app_production
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      DATABASE_HOST: db
      RAILS_SERVE_STATIC_FILES: "true"
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:
