---
openapi: 3.0.1
info:
  title: API Documentation
  version: v1
components:
  securitySchemes:
    cookie_auth:
      type: apiKey
      in: cookie
      name: session
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
    error:
      type: object
      properties:
        message:
          type: string
paths:
  "/api/sign_up":
    post:
      summary: Creates a user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password123
                    password_confirmation:
                      type: string
                      example: password123
                  required:
                  - email
                  - password
                  - password_confirmation
  "/api/sign_in":
    post:
      summary: Signs in a user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: user signed in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password123
                  required:
                  - email
                  - password
  "/api/current_user":
    get:
      summary: Retrieves current user
      tags:
      - Authentication
      security:
      - cookie_auth: []
      responses:
        '200':
          description: current user retrieved
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
        '401':
          description: unauthorized
  "/api/sign_out":
    delete:
      summary: Signs out current user
      tags:
      - Authentication
      security:
      - cookie_auth: []
      responses:
        '200':
          description: signed out successfully
  "/api/users":
    get:
      summary: Lists all users
      tags:
      - Users
      security:
      - cookie_auth: []
      responses:
        '200':
          description: users found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/user"
  "/api/users/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a user
      tags:
      - Users
      security:
      - cookie_auth: []
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
        '404':
          description: user not found
  "/api/profile":
    get:
      summary: Retrieves user profile
      tags:
      - Users
      security:
      - cookie_auth: []
      responses:
        '200':
          description: profile retrieved
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
        '401':
          description: unauthorized
  "/api/change_password":
    post:
      summary: Changes user password
      tags:
      - Users
      security:
      - cookie_auth: []
      parameters: []
      responses:
        '200':
          description: password changed
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  example: current123
                password:
                  type: string
                  example: new123
                password_confirmation:
                  type: string
                  example: new123
              required:
              - current_password
              - password
              - password_confirmation
servers:
- url: http://localhost:3000
